/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 10/03/2026 15:09:30          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE BASE_DADOS_DIARIO.GDB
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE COLLATION NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_ACORDAR;
SET GENERATOR GEN_ACORDAR TO 0;

CREATE GENERATOR GEN_ATIVIDADE;
SET GENERATOR GEN_ATIVIDADE TO 37;

CREATE GENERATOR GEN_CORPO;
SET GENERATOR GEN_CORPO TO 5;

CREATE GENERATOR GEN_INTERVALOTEMPO;
SET GENERATOR GEN_INTERVALOTEMPO TO 0;

CREATE GENERATOR GEN_MOVIMENTACAOHORA;
SET GENERATOR GEN_MOVIMENTACAOHORA TO 49;

CREATE GENERATOR GEN_TAREFAS;
SET GENERATOR GEN_TAREFAS TO 0;

CREATE GENERATOR GEN_TIPOATIVIDADE;
SET GENERATOR GEN_TIPOATIVIDADE TO 33;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE ACORDAR (
    ID       INTEGER NOT NULL,
    ACORDAR  TIMESTAMP
);

CREATE TABLE ATIVIDADE (
    ID                INTEGER NOT NULL,
    DESCRICAO         VARCHAR(100),
    OBS               VARCHAR(200),
    ID_TIPOATIVIDADE  INTEGER NOT NULL
);

CREATE TABLE CORPO (
    ID_CORPO  INTEGER NOT NULL,
    DATA      TIMESTAMP,
    PESO      NUMERIC(8,3),
    CINTURA   INTEGER,
    OBS       VARCHAR(250)
);

CREATE TABLE INTERVALOTEMPO (
    ID                   INTEGER NOT NULL,
    TEMPOINICIAL         TIMESTAMP,
    TEMPOFINAL           TIMESTAMP,
    ID_MOVIMENTACAOHORA  INTEGER NOT NULL
);

CREATE TABLE MOVIMENTACAOHORA (
    ID            INTEGER NOT NULL,
    DATA          TIMESTAMP,
    OBS           VARCHAR(500),
    QTDE_HORAS    TIME,
    ACORDAR       TIME,
    ID_ATIVIDADE  INTEGER NOT NULL
);

CREATE TABLE TAREFAS (
    ID_TAREFA        INTEGER NOT NULL,
    DATA             TIMESTAMP,
    OBS              VARCHAR(250),
    DATA_FINALIZADO  TIMESTAMP,
    OPCAO            CHAR(1)
);

CREATE TABLE TIPOATIVIDADE (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(30)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE ACORDAR ADD PRIMARY KEY (ID);
ALTER TABLE ATIVIDADE ADD PRIMARY KEY (ID);
ALTER TABLE INTERVALOTEMPO ADD PRIMARY KEY (ID);
ALTER TABLE MOVIMENTACAOHORA ADD PRIMARY KEY (ID);
ALTER TABLE TIPOATIVIDADE ADD PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ATIVIDADE ADD FOREIGN KEY (ID_TIPOATIVIDADE) REFERENCES TIPOATIVIDADE (ID);
ALTER TABLE INTERVALOTEMPO ADD FOREIGN KEY (ID_MOVIMENTACAOHORA) REFERENCES MOVIMENTACAOHORA (ID);
ALTER TABLE MOVIMENTACAOHORA ADD FOREIGN KEY (ID_ATIVIDADE) REFERENCES ATIVIDADE (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CODIGO_ACORDAR */
CREATE TRIGGER CODIGO_ACORDAR FOR ACORDAR
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.ID = gen_id(gen_ACORDAR,1);
 end
^

/* Trigger: CODIGO_ATIVIDADE */
CREATE TRIGGER CODIGO_ATIVIDADE FOR ATIVIDADE
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.ID = gen_id(gen_atividade,1);
 end
^

/* Trigger: CODIGO_CORPO */
CREATE TRIGGER CODIGO_CORPO FOR CORPO
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id_corpo = gen_id(gen_corpo,1);
 end
^

/* Trigger: CODIGO_INTERVALOTEMPO */
CREATE TRIGGER CODIGO_INTERVALOTEMPO FOR INTERVALOTEMPO
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id = gen_id(gen_intervalotempo,1);
 end
^

/* Trigger: CODIGO_MOVIMENTACAOHORA */
CREATE TRIGGER CODIGO_MOVIMENTACAOHORA FOR MOVIMENTACAOHORA
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id = gen_id(gen_movimentacaohora,1);
 end
^

/* Trigger: CODIGO_TAREFAS */
CREATE TRIGGER CODIGO_TAREFAS FOR TAREFAS
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.id_tarefa = gen_id(gen_tarefas,1);
 end
^

/* Trigger: CODIGO_TIPOATIVIDADE */
CREATE TRIGGER CODIGO_TIPOATIVIDADE FOR TIPOATIVIDADE
ACTIVE BEFORE INSERT POSITION 0
as
 begin
  new.ID = gen_id(gen_tipoatividade,1);
 end
^

SET TERM ; ^

